# Generated by Django 4.2.7 on 2023-12-12 23:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_options_page_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='order',
            field=ckeditor.fields.RichTextField(default=0, verbose_name='Orden'),
        ),
    ]
